layout_spectrum: 0.6477749
typography_spectrum: 0.2164083
color:
  saturation: 0.1003986
  lightness: 0.2901496
  brandStrength: 0.5580295
  rhythmicContrast: 0.5323494
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Hakan Aldrin Photohraphy
